### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by mmstick**
- Releases nvidia-docker2 and nvidia-container-toolkit
- Contains fixes for pop-launcher, pop-shell, and cosmic-workspaces

### CODE REVIEW

**Review by leviport — APPROVED** [review]
Approved, assuming we're good to release the `popsec` package that's been sitting in limbo for a while

**Comment by amenophis** [comment]
There is a critical bug with Intellij IDEA software. Do you think this release will be available quickly ?

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
@amenophis we don't manage Intellij IDEA releases, where did you get it from?

**Comment by nickistre** [comment]
@leviport 
> There is a critical bug with Intellij IDEA software. Do you think this release will be available quickly ?

I don't think it's a "critical" bug per-say.  Extremely annoying bug, yes, but it does have a workaround. I am with you waiting for the fix to be rolled out, but I don't know what the Pop OS release process is like once the changes are merged into `master` here.  

Running `sudo apt update && apt policy pop-shell` does show that a new candidate is out for me now, though:
```
Hit:1 http://apt.pop-os.org/proprietary impish InRelease
Get:2 http://apt.pop-os.org/release impish InRelease [6,850 B]                                                                                                       
Hit:3 https://d20adtppz83p9s.cloudfront.net/GTK/latest/debian-repo ubuntu-20.04 InRelease                                                                                                              
Hit:4 http://us.archive.ubuntu.com/ubuntu impish InRelease                                                                                                           
Get:5 http://us.archive.ubuntu.com/ubuntu impish-security InRelease [110 kB]
Hit:6 http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu hirsute InRelease
Get:7 http://apt.pop-os.org/release impish/main Sources [61.7 kB]
Get:8 http://apt.pop-os.org/release impish/main amd64 Packages [129 kB]        
Get:9 http://apt.pop-os.org/release impish/main i386 Packages [66.5 kB]
Hit:10 http://us.archive.ubuntu.com/ubuntu impish-updates InRelease                        
Get:11 http://us.archive.ubuntu.com/ubuntu impish-backports InRelease [101 kB]
Fetched 475 kB in 1s (532 kB/s)     
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
7 packages can be upgraded. Run 'apt list --upgradable' to see them.
pop-shell:
  Installed: 1.1.0~1641595320~21.10~c3d93f8
  Candidate: 1.1.0~1642015119~21.10~b3b2e35
  Version table:
     1.1.0~1642015119~21.10~b3b2e35 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
 *** 1.1.0~1641595320~21.10~c3d93f8 100
        100 /var/lib/dpkg/status
```

**Comment by amenophis** [comment]
Modal window in the application can't be opened, so, seems a bit critical 😅

**Comment by tobias-reese** [comment]
Any idea when this will be available for focal? I see the commit contains a version 1.1.0~1642015119~20.04 but updating packages does not provide me the update.

**Comment by mmstick** [comment]
@tobias-reese I will release it there

**Pull request merged**
